### ISSUE TITLE
why is every element processed?

### ISSUE THREAD

**Issue by tommedema** [punkave/absolution#3]
while trying to make a PR for #1 I noticed that you are looping over every element with `htmlparser2` and then reconstructing the element. This depends on knowing exactly which elements are self-closing etc. It seems rather risky -- I would normally only do this for elements that actually have a url.

Is there a reason why it seems to be reconstructing elements that do not have urls too?

**Comment by tommedema** [comment]
For example, this causes unintended effects like `<author name="" />` to become `<author name />`

This library should not touch elements that it does not relate to in my opinion.

**Comment by boutell** [comment]
The htmlparser2 module, for better or worse, does not provide the original representation, and so we must output a new representation. The representation we are outputting is equivalent; the example you give does not change the interpretation by the browser, javascript, etc. in any way.
